services:
  KL-backend:
    image: ghcr.io/bazaaer/asocialnetwork-api:latest
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # Backend
      - "traefik.http.routers.KL-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.KL-backend.entrypoints=websecure"
      - "traefik.http.services.KL-backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.KL-backend.tls=true"
      - "traefik.http.routers.KL-backend.tls.certresolver=letsencrypt"
    deploy:
      replicas: 2  # Duplicates the service to run 2 instances
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true