services:
  backend:
    image: ghcr.io/bazaaer/asocialnetwork-api:latest
    runtime: nvidia  # Use NVIDIA runtime for GPU support
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network

volumes:
  mongodb_data:

networks:
  traefik:
    external: true
  internal_network:
    driver: bridge